### ISSUE TITLE
Slides for the final presentation

### ISSUE THREAD

**Issue by noe** [telecombcn-dl/2018-dlai#1]
Please add a comment specifying which team you are and a link to the slides you are going to use for the presentation.

**Comment by jannaescur** [comment]
Hi Noe, we are team 1 and you can find the slides that we will use tomorrow here: https://docs.google.com/presentation/d/119qbyrIztQBtWYJUOGAqLyCzlxH7kQjvdRvuFaKLLm0/edit?usp=sharing
Thanks!

**Comment by michakrzeminski** [comment]
We are team 2, presentation: https://docs.google.com/presentation/d/1KbOqkZ32rrUDvKVwFVwnQfXCpOQTquJuN72NNk9Gjzc/edit?usp=sharing

**Comment by jorditruji** [comment]
Hello, 
Slides for group 8: https://docs.google.com/presentation/d/1Taxxd7D1DdKF4jT7px0XVfaMKDnMv3SrU49_OBrRJNM/edit?usp=sharing

**Comment by qdeleuil** [comment]
Hello, 

Slides for group 4 : 
https://docs.google.com/presentation/d/1ZOf1vZDVHB_LIyCpWRZR4FqqcZY08Dc_GMsER3ziRaM/edit?usp=sharing

**Comment by presmerats** [comment]
Hello,
slides for group 3:
https://docs.google.com/presentation/d/1l5hy0Sn1Gt5IJiXVK1X8932JHo17K75us-PzseX5KPU/edit?usp=sharing

**Comment by marionacaros** [comment]
Hello we are team 9, our link: https://docs.google.com/presentation/d/1zaVE6nkZuXNcNz3RTT8aobpBLgapAXHVL6GyDjOYrUs/edit?usp=sharing

**Comment by MarcHernandez** [comment]
Hello, we are team 5, our link:

**Comment by MarcHernandez** [comment]
Hello, we are team 5, our link:

https://docs.google.com/presentation/d/11hlxL5RFY-Jlpbo2oiuLQvDNPw0Tp8f9rsSK22OSwhM/edit?ts=5c14c9d5#slide=id.g4a84fb7cf2_4_29

**Comment by Darchek** [comment]
Hi Noe, we are team 10, here you have our link:

https://docs.google.com/presentation/d/1WF52LlN8Uct_DYW8Mkl0FrXXIh8d2WiEmleA7XEzsJ4/edit?usp=sharing

**Comment by xavigiro** [comment]
I also share here [my slides](https://docs.google.com/presentation/d/1HRh1yoCb5pUJtScBnxKTVnF73ozgRr-LNy-cEdIYPAk/edit?usp=sharing) for the final session.
